IMAP_SERVER = "imap.gmail.com"
IMAP_PORT = 993

EMAIL_ACCOUNT = "YOUR_EMAIL_ID"
EMAIL_PASSWORD = "YOUR_APP_PASSWORD"
ORGANIZATION_DOMAIN = "gmail.com"

PHISHING_THRESHOLD = 15
SUSPICIOUS_THRESHOLD = 10
